#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
# [新增] 为 trace 系统调用生成用户态汇编桩（见上方 entry 子程序）：
# 生成的内容等价于：
#   .global trace
#   trace:
#     li a7, SYS_trace   # 把系统调用号 22 放入 a7 寄存器
#     ecall              # 触发 ecall 指令陷入内核态
#     ret                # 内核返回后回到用户态调用者
# 没有这个桩，用户程序调用 trace() 时会链接失败（undefined reference）。
entry("trace");
# [新增] 为 sysinfo 系统调用生成用户态汇编桩，原理同上：
#   .global sysinfo
#   sysinfo:
#     li a7, SYS_sysinfo # 把系统调用号 23 放入 a7 寄存器
#     ecall              # 陷入内核态（用户指针已在 a0 里，正好是第 0 个参数）
#     ret                # 返回用户态，a0 中是内核的返回值（0 成功 / -1 失败）
# 没有这个桩，用户程序调用 sysinfo() 时会链接失败（undefined reference）。
entry("sysinfo");
